      {
        ".read": true,
        ".write": true
      },
      "subscribers",
      "reports",
      "analytics_events",
      "user_consents",
      "site_settings",
      "users",
      "comments",
      "notifications",
      "messages",
      "media",
      "ads",
      "matches",
      "flashes",
      "dispatches",
      "relations",
      "blocks",
      "discussions",
      "rss_drafts",
      "preferences"