awk '/const loginWithEmail = async/ { 
  print "  const loginWithGoogle = async () => {"
  print "    try {"
  print "      const provider = new GoogleAuthProvider();"
  print "      const result = await realSignInWithPopup(realFirebaseAuth, provider);"
  print "      const u = result.user;"
  print "      const cleanEmail = u.email ? u.email.toLowerCase().trim() : \"\";"
  print "      if (!cleanEmail) throw new Error(\"No email returned from Google\");"
  print "      const userDocRef = doc(db, \"users\", cleanEmail);"
  print "      const userDoc = await getDoc(userDocRef);"
  print "      let profileObj;"
  print "      if (userDoc.exists()) {"
  print "        const data = userDoc.data();"
  print "        const isAdminUser = cleanEmail === \"kadersdiaz3@gmail.com\" || cleanEmail === \"admin@perspective.sn\" || data.role === \"Admin\" || cleanEmail.includes(\"admin\");"
  print "        profileObj = {"
  print "          ...data,"
  print "          id: data.id || u.uid,"
  print "          name: data.name || u.displayName || cleanEmail.split(\"@\")[0],"
  print "          email: cleanEmail,"
  print "          avatarUrl: data.avatarUrl || u.photoURL || \"preset-male\","
  print "          role: isAdminUser ? \"Admin\" : (data.role || \"Member\"),"
  print "          isFirebase: true"
  print "        };"
  print "        await setDoc(userDocRef, { ...profileObj, lastLoginAt: new Date().toISOString() }, { merge: true });"
  print "      } else {"
  print "        const isAdminUser = cleanEmail === \"kadersdiaz3@gmail.com\" || cleanEmail === \"admin@perspective.sn\" || cleanEmail.includes(\"admin\");"
  print "        profileObj = {"
  print "          id: u.uid,"
  print "          name: u.displayName || cleanEmail.split(\"@\")[0],"
  print "          email: cleanEmail,"
  print "          avatarUrl: u.photoURL || \"preset-male\","
  print "          role: isAdminUser ? \"Admin\" : \"Member\","
  print "          emailVerified: true,"
  print "          mfaEnabled: false,"
  print "          isFirebase: true,"
  print "          coverPhotoUrl: \"https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=600&fit=crop\","
  print "          streak: 1,"
  print "          readingTime: 0,"
  print "          hidePersonalInfo: false,"
  print "          bio: \"Membre lecteur\","
  print "          accolades: [\"verified_identity\"]"
  print "        };"
  print "        await setDoc(userDocRef, { ...profileObj, registeredAt: new Date().toISOString(), lastLoginAt: new Date().toISOString() }, { merge: true });"
  print "      }"
  print "      setReaderProfile(profileObj);"
  print "      // Update fake Mongo auth service to sync state if needed"
  print "      try { await auth.register(cleanEmail, \"google_oauth_pass_ignored\", profileObj.name); } catch(e){}"
  print "    } catch (err) {"
  print "      console.error(\"Google sign in error:\", err);"
  print "      throw err;"
  print "    }"
  print "  };"
  print ""
} 
{print}' src/contexts/AuthContext.tsx > temp.tsx && mv temp.tsx src/contexts/AuthContext.tsx
