awk '/const handleAuthSubmit = async/ {
  print "  const handleGoogleSignIn = async () => {"
  print "    setIsSubmitting(true);"
  print "    setErrorMessage(\"\");"
  print "    setSuccessMessage(\"\");"
  print "    try {"
  print "      await loginWithGoogle();"
  print "      if (authTab === \"newsletter\") {"
  print "         const gUser = realFirebaseAuth.currentUser;"
  print "         if (gUser && gUser.email) {"
  print "           await addSubscriber(gUser.email);"
  print "           setSuccessMessage(language === \"fr\" ? \"Abonnement réussi !\" : \"Subscription successful!\");"
  print "         }"
  print "      } else {"
  print "         navigate(\"/admin\");"
  print "      }"
  print "    } catch (err: any) {"
  print "      setErrorMessage(err.message || \"Google sign in failed\");"
  print "    } finally {"
  print "      setIsSubmitting(false);"
  print "    }"
  print "  };"
  print ""
}
{print}' src/pages/AuthPage.tsx > temp.tsx && mv temp.tsx src/pages/AuthPage.tsx
